name: Update Google Sheet

on:
  workflow_dispatch: # allows manual run
  # schedule:
  #  - cron: '0 * * * *' # runs every hour

jobs:
  update-sheet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread google-auth

      - name: Run the script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: python script.py
